import type { Product } from "@/features/catalog/domain/product";

export const mockProducts: Product[] = [
  {
    id: "1",
    code: "FZ3067",
    image: "/images/catalog/mock_image.jpg",
    images: [
      "/images/catalog/mock_image.jpg?view=1",
      "/images/catalog/mock_image.jpg?view=2",
      "/images/catalog/mock_image.jpg?view=3",
    ],
    rank: "Platinum 1",
    price: 650000,
    skins: [
      "Reaver Vandal 2024 Limited Championship Edition Ultra Glow",
      "Prime Phantom Spectrum Bundle Anniversary Variant",
      "Glitchpop Classic Neon Overdrive Finisher Collection",
      "Ion Sheriff Prototype Series Clean Energy Finish",
      "Oni Katana Moonlit Festival Signature Variant",
      "Magepunk Spectre Electrostatic Night Market Edition",
      "Protocol Bulldog Sentient Core Tactical Frame",
      "ChronoVoid Judge Celestial Rift Signature Finish",
      "Sentinels of Light Operator Radiant Crown Edition",
      "Xerofang Ghost Crimson Fang Collector Variant",
    ],
    sisaVP: "-",
    agent: "Full Unlock",
    changeNick: "Ready",
    region: "IDN",
    premier: "",
    status: "available",
  },
  {
    id: "2",
    code: "FZ2044",
    image: "/images/catalog/mock_image.jpg",
    images: [
      "/images/catalog/mock_image.jpg?view=1",
      "/images/catalog/mock_image.jpg?view=2",
    ],
    rank: "Diamond 2",
    price: 1200000,
    skins: [
      "Champions Vandal World Tour Legacy Signature Edition",
      "Oni Phantom Celestial Mask Premium Masterwork",
      "Sovereign Ghost Radiant Crest Exclusive Finish",
    ],
    sisaVP: "320",
    agent: "Full Unlock",
    changeNick: "Ready",
    region: "IDN",
    premier: "Unranked",
    status: "available",
    featured: "hot",
  },
  {
    id: "3",
    code: "FZ1891",
    image: "/images/catalog/mock_image.jpg",
    rank: "Gold 3",
    price: 350000,
    skins: ["Spectrum Phantom", "Elderflame Vandal"],
    sisaVP: "-",
    agent: "20/23",
    changeNick: "Ready",
    region: "IDN",
    premier: "Can't be changed",
    status: "available",
    featured: "best-deal",
  },
  {
    id: "4",
    code: "FZ4120",
    image: "/images/catalog/mock_image.jpg",
    rank: "Ascendant 1",
    price: 1800000,
    skins: [
      "Champions 2022 Vandal",
      "RGX Vandal",
      "Reaver Operator",
      "Ion Sheriff",
    ],
    sisaVP: "1200",
    agent: "Full Unlock",
    changeNick: "Ready",
    region: "IDN",
    premier: "Gold",
    status: "sold",
  },
  {
    id: "5",
    code: "FZ5500",
    image: "/images/catalog/mock_image.jpg",
    rank: "Silver 3",
    price: 200000,
    skins: ["Prime Vandal", "Sakura Vandal"],
    sisaVP: "-",
    agent: "15/23",
    changeNick: "Not Ready",
    region: "IDN",
    premier: "Can't be changed",
    status: "available",
  },
  {
    id: "6",
    code: "FZ6789",
    image: "/images/catalog/mock_image.jpg",
    rank: "Immortal 1",
    price: 2500000,
    skins: ["Champions Phantom", "Prelude Vandal", "Arcane Sheriff", "BlastX Odin"],
    sisaVP: "800",
    agent: "Full Unlock",
    changeNick: "Ready",
    region: "IDN",
    premier: "Diamond",
    status: "available",
    featured: "rare",
  },
];
